forms_else/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

forms_else/cars/urls.py
from django.urls import path

from . import views

app_name = "cars"
urlpatterns = [
    path("main", views.main, name="main"),
    path("log", views.log, name="log"),
    path("log_in", views.log_in, name="log_in"),
    path("lookup", views.MakeView.as_view(), name="lookup"),
    path("lookup/create", views.MakeCreate.as_view(), name="mcreate"),
    path("lookup/<int:pk>/update", views.MakeUpdate.as_view(), name="mupdate"),
    path("lookup/<int:pk>/delete", views.MakeDelete.as_view(), name="mdelete"),
    path("cars", views.CarView.as_view(), name="cars"),
    path("cars/create", views.CarCreate.as_view(), name="ccreate"),
    path("cars/<int:pk>/update", views.CarUpdate.as_view(), name="cupdate"),
    path("cars/<int:pk>/delete", views.CarDelete.as_view(), name="cdelete"),
    # path("update", views.Update.as_view(), name="update"),

]

forms_else/forms_else/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("formok/", include("formok.urls")),
    path("cars/", include("cars.urls")),
    path("cats/", include("cats.urls")),
    path("arts/", include("myarts.urls")),
    path("ads/", include("ads.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
]

forms_else/cars/models.py
from django.core import validators
from django.core.validators import MinLengthValidator
from django.db import models


# Create your models here.
# class Cars(models.Model):
#     nickname = models.CharField(max_length=255)
#     make = models.CharField(max_length=255, blank=True)
#     mileage = models.IntegerField()
#     comments = models.TextField(blank=True)

class Make(models.Model):
    name = models.CharField(
        max_length=255,
        help_text="Enter a make (pl. Ford):",
        validators=[MinLengthValidator(2)]
    )

    def __str__(self):
        return self.name


class Auto(models.Model):
    nickname = models.CharField(
        max_length=255,
        validators=[MinLengthValidator(2)]
    )
    make = models.ForeignKey("Make", on_delete=models.CASCADE)
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.nickname

forms_else/cars/forms.py
from django import forms
from django.core.validators import MinLengthValidator
from django.forms import ModelForm
from rest_framework import serializers

# from .models import Cars
from .models import Make


# #WORKS
# class CarForm(ModelForm):
#     class Meta:
#         model = Cars
#         fields = "__all__"
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['mileage'] = forms.IntegerField(min_value=0)
#         self.fields["nickname"] = forms.CharField(min_length=2, max_length=255)


class MakeForm(forms.ModelForm):
    class Meta:
        model = Make
        fields = "__all__"

forms_else/cars/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
# from .forms import CarForm
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import UpdateView, CreateView, DeleteView

from .forms import MakeForm
from .models import Make, Auto

base = "cars/templates/"


def main(request):
    return render(request, base + "main.html")


def log(request):
    return render(request, base + "registration/login.html")


def log_in(request):
    if request.method == "POST":
        name = request.POST["name"]
        password = request.POST["password"]

        user = authenticate(request, username=name, password=password)

        if user is not None:
            login(request, user)
            # return redirect(reverse("main"))
            return redirect(reverse("cars:main"))
        else:
            messages.add_message(request, messages.INFO, 'Invalid credentials.')
            return redirect(reverse("cars:main"))


class MakeView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Make.objects.all()
        return render(request, base + "make_list.html", {"make_list": ml})


class MakeCreate(LoginRequiredMixin, View):
    template = base + "make_form.html"
    # success_url = base+"make_form.html"
    success_url = reverse_lazy('cars:main')

    def get(self, request):
        form = MakeForm()
        return render(request, self.template, {"form": form})

    def post(self, request):
        form = MakeForm(request.POST)
        if not form.is_valid():
            return render(request, self.template, {"form": form})
        form.save()
        return redirect(self.success_url)


class MakeUpdate(LoginRequiredMixin, View):
    model = Make
    template = base + "make_form.html"
    success_url = reverse_lazy('cars:main')

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance=make)
        return render(request, self.template, {"form": form})

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(request.POST, instance=make)
        if not form.is_valid():
            return render(request, self.template, {"form": form})
        form.save()
        return redirect(self.success_url)


class MakeDelete(LoginRequiredMixin, View):
    model = Make
    template = base + "make_confirm_delete.html"
    success_url = reverse_lazy('cars:main')

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance=make)
        return render(request, self.template, {"form": form})

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        make.delete()
        return redirect(reverse("cars:main"))


class CarView(LoginRequiredMixin, View):
    model = Auto
    template = base + "car_list.html"

    def get(self, request):
        car_list = Auto.objects.all()
        make_count = Make.objects.all().count()
        return render(request, self.template, {"auto_list": car_list, "make_count": make_count})


class CarCreate(LoginRequiredMixin, CreateView):
    model = Auto
    fields = "__all__"
    template_name = "cars/templates/auto_form.html"
    success_url = reverse_lazy('cars:main')


class CarUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = "__all__"
    template_name = "cars/templates/auto_form.html"
    success_url = reverse_lazy('cars:main')


class CarDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = "__all__"
    template_name = "cars/templates/car_confirm_delete.html"
    success_url = reverse_lazy('cars:main')

forms_else/cars/templates/auto_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cars:main' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

</body>
</html>

forms_else/cars/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
{% comment %}
<!-- Replace this value (42-42) with the one provided by the autograder -->
{% endcomment %}
    <meta name="dj4e" content="42-42">

<meta name="dj4e-code" content="99999999">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-12-22">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

forms_else/cars/templates/car_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

</body>
</html>

forms_else/cars/templates/car_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auto List</title>
</head>
<body>
{% extends "base_bootstrap.html" %}
{% block content %}

<h1>Auto List</h1>
{% if auto_list %}
<ul>
    {% for auto in auto_list %}
    <li>
        {{ auto.nickname }} ({{ auto.make }})

        (<a href="{% url 'cars:cupdate' auto.id %}">Update</a> |
        <a href="{% url 'cars:cdelete' auto.id %}">Delete</a>)

        <br/>
        {{ auto.comments }} ({{ auto.mileage }} miles)
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no autos in the library.</p>
{% endif %}
<p>
    {% if make_count > 0 %}

    <a href="{% url 'cars:ccreate' %}">Add an auto</a>

    {% else %}
    Please add a make before you add an auto.
    {% endif %}

</p>
<p>

    <a href="{% url 'cars:lookup' %}">View makes</a> ({{ make_count }}) |
    <a href="{% url 'cars:mcreate' %}">Add a make</a>

</p>

{% endblock%}

</body>
</html>

forms_else/cars/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Page</title>
</head>
<body style="background-color:#40E0D0; color:white">
{% if user.is_authenticated %}
<h1>Hello, {{user.username}}!</h1>
{% else %}
<h1>Hello, guest!</h1>
{% endif %}

<form action="{% url 'cars:log' %}">
    <h2>Go to log in page!</h2>
    <input type="submit" value="Go">
</form>

<form action="{% url 'cars:lookup' %}">
    <h2>Go to Make List!</h2>
    <input type="submit" value="Go">
</form>

<form action="{% url 'cars:cars' %}">
    <h2>Go to Auto List!</h2>
    <input type="submit" value="Go">
</form>


{% comment %}
<!--<form action="" method="post">-->
<!--    {% csrf_token %}-->
<!--    <table>{{form.as_table}}</table>-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->
{% endcomment %}
</body>
</html>

forms_else/cars/templates/make_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>M del</title>
</head>
<body>
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cars:main' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

</body>
</html>

forms_else/cars/templates/make_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make Form</title>
</head>
<body>

{% extends "base_bootstrap.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}


    <p>
        {{ form.as_p }}
    </p>


    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cars:main' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

</body>
</html>

forms_else/cars/templates/make_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Make List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'cars:mupdate' make.id %}">Update</a> |

          <a href="{% url 'cars:mdelete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes in the library.</p>
  {% endif %}
  <p><a href="{% url 'cars:mcreate' %}">Add a make</a></p>
  <p>
    <a href="{% url 'cars:main' %}">Back to autos</a>
  </p>
{% endblock %}

</body>
</html>