forms_else/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

forms_else/formok/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name="formok"
base="formok/templates/crispy/"
urlpatterns = [
    path("example", views.example, name="example"),
    path("main", views.main, name="main"),
    path("create", views.Create.as_view(), name="create"),
    path("update", views.Update.as_view(), name="update"),
    path('validate', views.ClassValid.as_view(), name="validate"),
    path("success", views.success, name="success"),
    path("nothing", TemplateView.as_view(template_name=base+"main.html"), name="nothing"),
    path("boring", views.MyView.as_view(template_name=base+"boring.html"), name="boring"),
    path("awesome", views.MyView.as_view(template_name=base+"awesome.html"), name="awesome"),
]

forms_else/forms_else/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("formok/", include("formok.urls")),
    path("cars/", include("cars.urls")),
    path("cats/", include("cats.urls")),
    path("arts/", include("myarts.urls")),
    path("ads/", include("ads.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
]

forms_else/formok/models.py
from django.db import models

# Create your models here.

forms_else/formok/forms.py
from django import forms
from django.core import validators


class BasicForm(forms.Form):
    title = forms.CharField(validators=[validators.MinLengthValidator(2, "pls enter 2 or more characters")])
    mileage = forms.IntegerField()
    purchase_date = forms.DateField()

forms_else/formok/views.py
import html

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from .forms import BasicForm

base = "formok/templates/"


def example(request):
    form = BasicForm()
    return HttpResponse(form.as_table())  # !!!


def main(request):
    return render(request, base + "main.html")


def dumpdata(place, data):
    retval = ""
    if len(data) > 0:
        retval += '<p>Incoming ' + place + ' data:<br/>\n'
        for k, v in data.items():
            retval += html.escape(k) + "=" + html.escape(v) + '</br>\n'
        retval += '</p>\n'
    return retval


class DumpPostView(View):
    def post(self, request):
        dump = dumpdata("POST", request.POST)
        ctx = {'title': 'request.POST', "dump": dump}
        return render(request, base + 'dump.html', ctx)


class Create(DumpPostView):
    def get(self, request):
        form = BasicForm()
        ctx = {"form": form}
        return render(request, base + "form.html", ctx)


class Update(DumpPostView):
    def get(self, request):
        old_data = {
            'title': 'SakaiCar',
            'mileage': 42,
            'purchase_date': '2018-08-14'
        }
        form = BasicForm(old_data)
        ctx = {"form": form}
        return render(request, base + "form.html", ctx)


class ClassValid(DumpPostView):
    def get(self, request):
        old_data = {
            'title': 'SakaiCar',
            'mileage': 42,
            'purchase_date': '2018-08-14'
        }
        form = BasicForm(old_data)
        ctx = {"form": form}
        return render(request, base + "form.html", ctx)

    def post(self, request):
        form = BasicForm(request.POST)
        if not form.is_valid():
            ctx = {"form": form}
            return render(request, base + "form.html", ctx)
        return redirect(reverse("formok:success"))


def success(request):
    return HttpResponse('Yo nice!')


class MyView(View):
    template_name=None
    def get(self, request):
        old_data = {
            'title': 'SakaiCar',
            'mileage': 42,
            'purchase_date': '2018-08-14'
        }
        form = BasicForm(old_data)
        ctx = {"form": form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = BasicForm(request.POST)
        if not form.is_valid():
            ctx = {"form": form}
            return render(request, self.template_name, ctx)
        messages.add_message(request, messages.SUCCESS, "Data saved")
        return redirect(reverse("formok:nothing"))

forms_else/formok/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
{% comment %}
<!-- Replace this value (42-42) with the one provided by the autograder -->
{% endcomment %}
    <meta name="dj4e" content="42-42">

<meta name="dj4e-code" content="99999999">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-12-22">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

forms_else/formok/templates/dump.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dump</title>
</head>
<body style="background-color:lightblue; color:white;">
<p>Dump of {{title}}:</p>
<p>{{dump|safe}}</p>
<!--safe tells dj that content needs no further processing-> already escaped-->
<a href="{% url 'formok:main' %}">Back</a>
</body>
</html>

forms_else/formok/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Example form</title>
</head>
<body style="background-color:lightblue; color:white;">
<h1>FORM PAGE bitcheees</h1>


<p>
<form method="POST" action="">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    <br>
    <input type = "submit" value = "Submit">
    <input type = "submit" onclick="window.location='{% url 'formok:main' %}'; return false;" value="Cancel">
<!--    <h2>Data:</h2>-->
<!--    <ul>-->
<!--        <li>-->
<!--    <p>Title:-->
<!--    <input type = "text" name = "title" id="title"></p>-->
<!--        </li><li>-->
<!--    <p> Mileage:-->
<!--    <input type = "number" name = "mileage" id="mileage"></p>-->
<!--        </li><li>-->
<!--    <p>Purchase date:-->
<!--    <input type = "date" name = "purchase_date" id="purchase_date"></p>-->
<!--        </li>-->
<!--        </ul>-->
</form>
</p>
</body>
</html>

forms_else/formok/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
</head>
<body style="background-color:lightblue; color:white;">
<ul>
    <li><a href="example">Raw output of form.as_table</a></li>
    <li><a href="create">Simple create view</a></li>
    <li><a href="update">Simple update view</a></li>
    <li><a href="validate">Form validation</a>
        (<a href="https://docs.djangoproject.com/en/3.0/ref/forms/validation/" target="_blank">Documentation</a>)
    <li><a href="meow">Cat create view</a></li>
    <li><a href="cat/1/update">Cat update view</a> (The key might be wrong)</li>
    </li>
</ul>
</body>
</html>